const data = [
           [
            {
              genreEn: 'jadval',
              genreFarsi: 'جدول',
              genreId: 'wet',
              type: 'وت پرس',
              img: '/images/jadval/mobile/40.jpg',
              sizes: [
                {
                  type: '50*30*10',
                  price: '42300',
                  shipping: '3000',
                },
                {
                  type: '50*30*12.5',
                  price: '47000',
                  shipping: '3000',
                },

               {
                  type: '50*30*15',
                  price: '52800',
                  shipping: '3000',
                },
              ],
            },
            {
                genreEn: 'jadval',
              genreId: 'kush',
              type: 'پرس خشك',
              img: '/images/jadval/mobile/50.jpg',
              sizes: [
                 {
                  type: '50*30*10',
                  price: '38500',
                  shipping: '3000',
                },
                {
                  type: '50*40*15',
                  price: '62000',
                  shipping: '3000',
                },
                 {
                  type: '50*50*15',
                  price: '65000',
                  shipping: '3000',
                },
              ],
            },
            {
                genreEn: 'jadval',
              genreId: 'hand',
              type: 'دستي',
              img: '/images/jadval/mobile/d1.jpg',
              sizes: [
                {
                  type: '50*30*6',
                  price: '42300',
                  shipping: '3000',
                },
                 {
                  type: '50*30*8',
                  price: '47000',
                  shipping: '3000',
                },
                {
                  type: '50*30*10',
                  price: '52800',
                  shipping: '3000',
                },
              ],
            },
          ],
          [
            {
              genreEn: 'blook',
              genreFarsi: 'بلوك',
              genreId: 'pooke',
              type: 'سبك پوكه',
              img: '/images/blook/mobile/pooke.jpg',
              sizes: [
               {
                  image: '#',
                  type: 'بلوک ته پر پوکه',
                  size: '40*20*20',
                  price: '12700',
                  shipping: '500',
                },
               {
                  image: '#',
                  type: 'بلوک ۵۰ پوکه',
                  size: '50*20*15',
                  price: '13600',
                  shipping: '500',
                },
                {
                  image: '#',
                  type: 'بلوک ۱۵ پوکه',
                  size: '40*20*15',
                  price: '11200',
                  shipping: '500',
                },
                {
                  image: '#',
                  type: 'تیغه ۱۰ پوکه فروه',
                  size: '40*20*10',
                  price: '9350',
                  shipping: '500',
                },
              ],
            },
            {
                genreEn: 'blook',
              genreId: 'simani',
              type: 'بلوك سيماني',
              img: '/images/blook/mobile/simani.jpg',
              sizes: [
                {
                  image: '#',
                  type: 'دیواری ته باز سیمانی',
                  size: '40*20*20',
                  price: '9800-10800',
                  shipping: '500',
                },
                 {
                  image: '#',
                  type: 'دیواری ته پر سیمانی',
                  size: '40*20*20',
                  price: '10800',
                  shipping: '500',
                },
                {
                  image: '#',
                  type: 'بلوک ۵۰ سیمانی',
                  size: '50*20*15',
                  price: '12000',
                  shipping: '500',
                },
                {
                  image: '#',
                  type: 'بلوک ۱۵ سیمانی',
                  size: '40*20*15',
                  price: '9400',
                  shipping: '500',
                },
               {
                  image: '#',
                  type: 'تیغه ۱۰ سیمانی',
                  size: '40*20*10',
                  price: '7600',
                  shipping: '500',
                },
                 {
                  image: '#',
                  type: 'بلوک سقفی سیمانی',
                  size: '40*20*25',
                  price: '10800',
                  shipping: '500',
                },
                 {
                  image: '#',
                  type: 'کرومیت سقفی سیمانی',
                  size: '68.5*20*20',
                  price: '15000',
                  shipping: '500',
                },
              ],
            },
          ],
          [
            {
              genreEn: 'kafpoosh',
              genreFarsi: 'كفپوش',
              genreId: 'khoshk',
              type: 'پرس خشك',
              img: '/images/kafpoosh/mobile/39.jpg',
              sizes: [
                {
                  img: '/images/kafpoosh/mobile/40x40.png',
                  type: '۴۰*۴۰ پرسی',
                  inSquarefeet: '۶/۲۵ عدد',
                  toosi: '205000',
                  red: '240000',
                  yellowmix: '280000',
                  shipping: '5000',
                },
                 {
                  img: '/images/kafpoosh/mobile/20x20.png',
                  type: '۲۰*۲۰ پرسی',
                  inSquarefeet: '۲۵ عدد',
                  toosi: '205000',
                  red: '240000',
                  yellowmix: '280000',
                  shipping: '5000',
                },
                 {
                  image: '#',
                  type: '۱۰*۲۰ پرسی',
                  inSquarefeet: '۴۹ عدد',
                  toosi: '205000',
                  red: '240000',
                  yellowmix: '280000',
                  shipping: '5000',
                },
                 {
                  image: '#',
                  type: '۵۰*۵۰ پرسی',
                  inSquarefeet: '۴ عدد',
                  toosi: '205000',
                  red: '240000',
                  yellowmix: '280000',
                  shipping: '5000',
                },
                 {
                  image: '#',
                  type: '۳۰*۳۰ پرسی',
                  inSquarefeet: '۱۱ عدد',
                  toosi: '205000',
                  red: '240000',
                  yellowmix: '280000',
                  shipping: '5000',
                },
                 {
                  image: '#',
                  type: '۴۰*۴۰ نابینایان پرسی',
                  inSquarefeet: '۶.۲۵ عدد',
                  toosi: '205000',
                  red: '240000',
                  yellowmix: '280000',
                  shipping: '5000',
                },
              ],
            },
            {
              genreEn: 'kafpoosh',
              genreId: 'press',
              type: 'وت پرس',
              img: '/images/kafpoosh/mobile.jpg',
                sizes: [
                    {
                        img: '/images/kafpoosh/wetpress/mobile/red.jpg',
                        type: '۵۰*۵۰*۸',
                        inSquarefeet: '۴ عدد',
                        toosi: '250000',
                        red: '300000',
                        yellowmix: '350000',
                        shipping: '5000',
                    },
                    {
                        img: '/images/kafpoosh/wetpress/mobile/yellow.jpg',
                        type: '۵۰*۵۰*۸',
                        inSquarefeet: '۴ عدد',
                        toosi: '250000',
                        red: '300000',
                        yellowmix: '350000',
                        shipping: '5000',
                    },
                    {
                        img: '/images/kafpoosh/wetpress/mobile/grey.jpg',
                        type: '۵۰*۵۰*۸',
                        inSquarefeet: '۴ عدد',
                        toosi: '250000',
                        red: '300000',
                        yellowmix: '350000',
                        shipping: '5000',
                    },
                ]
            },
            {
              genreEn: 'kafpoosh',
              genreId: 'vibrate',
              type: 'ويبره',
              img: '/images/kafpoosh/mobile/39.jpg',
              sizes: [
                 {
                  img: '/images/kafpoosh/mobile/i.png',
                  type: 'آی خشک چین',
                  inSquarefeet: '۲۳ عدد',
                  toosi: '125000',
                  red: '145000',
                  yellowmix: '175000',
                  shipping: '5000',
                },
                 {
                  img: '/images/kafpoosh/mobile/6zeli.png',
                  type: 'خشک چین ۶ گوش',
                  inSquarefeet: '۱۸ عدد',
                  toosi: '125000',
                  red: '145000',
                  yellowmix: '175000',
                  shipping: '5000',
                },
                 {
                  img: '/images/kafpoosh/mobile/puzzle.png',
                  type: 'خشک چین پازل',
                  inSquarefeet: '۱۶ عدد',
                  toosi: '125000',
                  red: '145000',
                  yellowmix: '175000',
                  shipping: '5000',
                },
                {
                  img: '/images/kafpoosh/mobile/tabbari.png',
                  type: 'خشک چین طبری',
                  inSquarefeet: '۲۸ عدد',
                  toosi: '125000',
                  red: '145000',
                  yellowmix: '175000',
                  shipping: '5000',
                },
                 {
                  img: '/images/kafpoosh/mobile/congere.png',
                  type: 'خشک چین کنگره',
                  inSquarefeet: '۱۶ عدد',
                  toosi: '125000',
                  red: '145000',
                  yellowmix: '175000',
                  shipping: '5000',
                },
                 {
                  img: '/images/kafpoosh/mobile/kandooyi.png',
                  type: 'خشک چین کندویی',
                  inSquarefeet: '۱۸ عدد',
                  toosi: '125000',
                  red: '145000',
                  yellowmix: '175000',
                  shipping: '5000',
                },
                {
                  img: '/images/kafpoosh/mobile/koozeyi.png',
                  type: 'خشک چین کوزه ای و شنی',
                  inSquarefeet: '۲۲ عدد',
                  toosi: '125000',
                  red: '145000',
                  yellowmix: '175000',
                  shipping: '5000',
                },
                 {
                  img: '/images/kafpoosh/mobile/ajori.png',
                  type: 'خشک چین آجری',
                  inSquarefeet: '۴۹ عدد',
                  toosi: '165000',
                  red: '195000',
                  yellowmix: '235000',
                  shipping: '5000',
                },
                {
                  img: '/images/kafpoosh/mobile/badbar.png',
                  type: 'بادبر',
                  inSquarefeet: '۲۲ عدد',
                  toosi: '125000',
                  red: '145000',
                  yellowmix: '175000',
                  shipping: '5000',
                },
                 {
                  img: '/images/kafpoosh/mobile/20x20.png',
                  type: '۲۰*۲۰ ساده پوست ماری',
                  inSquarefeet: '۲۵ عدد',
                  toosi: '145000',
                  red: '165000',
                  yellowmix: '195000',
                  shipping: '5000',
                },
                 {
                  img: '/images/kafpoosh/mobile/40x40.png',
                  type: '۴۰*۴۰ ساده پوست ماری',
                  inSquarefeet: '۶/۲۵ عدد',
                  toosi: '145000',
                  red: '165000',
                  yellowmix: '195000',
                  shipping: '5000',
                },
                 {
                  img: '/images/kafpoosh/mobile/lozipoostmari.png',
                  type: '۵ ضلعی ساده پوست ماری',
                  inSquarefeet: '۲۰ عدد',
                  toosi: '145000',
                  red: '165000',
                  yellowmix: '195000',
                  shipping: '5000',
                },
                {
                  img: '/images/kafpoosh/mobile/setareyi.png',
                  type: 'حیاطی ۴۰*۴۰ ستاره',
                  inSquarefeet: '۶/۲۵ عدد',
                  toosi: '125000',
                  red: '145000',
                  yellowmix: '175000',
                  shipping: '5000',
                },
                {
                  img: '/images/kafpoosh/mobile/yasaman.png',
                  type: 'حیاطی ۴۰*۴۰ یاسمن',
                  inSquarefeet: '۶/۲۵ عدد',
                  toosi: '125000',
                  red: '145000',
                  yellowmix: '175000',
                  shipping: '5000',
                },
                 {
                  img: '/images/kafpoosh/mobile/sekeyi.png',
                  type: 'حیاطی ۳۰*۳۰ سکه ای',
                  inSquarefeet: '۱۱ عدد',
                  toosi: '125000',
                  red: '145000',
                  yellowmix: '175000',
                  shipping: '5000',
                },
                {
                  img: '/images/kafpoosh/mobile/hayati.png',
                  type: 'حیاطی ۳۳*۳۳ قلوه سنگی',
                  inSquarefeet: '۹ عدد',
                  toosi: '125000',
                  red: '145000',
                  yellowmix: '175000',
                  shipping: '5000',
                },
              ],
            },
            {
              genreEn: 'kafpoosh',
              genreId: 'wash',
              type: 'واش بتن',
              img: '/images/kafpoosh/mobile.jpg',
              sizes: [
                {
                  img: '/images/kafpoosh/mobile/40x40.png',
                  type: '30x60',
                  inSquarefeet: '۴ عدد',
                  toosi: '250000',
                  red: '300000',
                  yellowmix: '350000',
                  shipping: '5000',
                },
                {
                  img: '/images/kafpoosh/mobile/40x40.png',
                  type: '40x40',
                  inSquarefeet: '۴ عدد',
                  toosi: '250000',
                  red: '300000',
                  yellowmix: '350000',
                  shipping: '5000',
                },
              ],
            },
          ],
         [
            {
              genreEn: 'dal',
              genreFarsi: 'دال بتني',
              genreId: 'light',
              type: 'ترافیک سبک',
              img: '/images/dal/mobile/39.jpg',
              sizes: [
                 {
                  type: '80*60*10',
                  price: '650000',
                  shipping: '20000',
                },
                 {
                  type: '100*60*10',
                  price: '770000',
                  shipping: '20000',
                },
                 {
                  type: '120*60*10',
                  price: '800000',
                  shipping: '20000',
                },
              ],
            },
            {
                genreEn: 'dal',
              genreId: 'heavy',
              type: 'ترافیک سنگین',
              img: '/images/dal/mobile/44.jpg',
              sizes: [
                 {
                  type: '80*60*15',
                  price: '770000',
                  shipping: '20000',
                },
                {
                  type: '100*60*15',
                  price: '930000',
                  shipping: '20000',
                },
                 {
                  type: '120*60*15',
                  price: '1000000',
                  shipping: '20000',
                },
                 {
                  type: '150*60*15',
                  price: '1470000',
                  shipping: '50000',
                },
                 {
                  type: '150*60*20',
                  price: '1830000',
                  shipping: '50000',
                },
                 {
                  type: '200*60*20',
                  price: '2300000',
                  shipping: '50000',
                },
              ],
            },
          ],
          [
            {
              genreEn: 'mozayik',
              genreFarsi: 'موزاییک',
              genreId: 'simple',
              type: 'ساده',
              img: '/images/mozayik/mobile/sade.jpg',
              sizes: [
                 {
                  img: '/images/kafpoosh/mobile/40x40',
                  type: 'ساده ایرانی ۳۰*۳۰ درجه ۱، درجه ۲',
                  inSquarefeet: '۱۱ عدد',
                  toosi: '90000/70000',
                  red: '-',
                  yellowmix: '-',
                  shipping: '5000',
                },
                 {
                  img: '/images/kafpoosh/mobile/40x40',
                  type: 'ساده ایرانی ۴۰*۴۰',
                  inSquarefeet: '۶​​/۲۵ عدد',
                  toosi: '100000',
                  red: '-',
                  yellowmix: '-',
                  shipping: '5000',
                },
                {
                  img: '/images/kafpoosh/mobile/40x40',
                  type: 'گرانیتی ساده ۴۰*۴۰',
                  inSquarefeet: '۶​​/۲۵ عدد',
                  toosi: '125000',
                  red: '-',
                  yellowmix: '-',
                  shipping: '5000',
                },
                {
                  img: '/images/kafpoosh/mobile/40x40',
                  type: 'مرمری ساده ۴۰*۴۰',
                  inSquarefeet: '۶​​/۲۵ عدد',
                  toosi: '125000',
                  red: '-',
                  yellowmix: '-',
                  shipping: '5000',
                },
              ],
            },
            {
                genreEn: 'mozayik',
              genreId: 'hayati',
              type: 'حياطي',
              img: '/images/mozayik/mobile.jpg',
              sizes: [
                {
                  img: '/images/kafpoosh/mobile/40x40',
                  type: 'موزائیک گرانیتی حیاطی ۴۰*۴۰',
                  inSquarefeet: '۶​​/۲۵ عدد',
                  toosi: '125000',
                  red: '-',
                  yellowmix: '-',
                  shipping: '5000',
                },
                 {
                  img: '/images/kafpoosh/mobile/40x40',
                  type: 'موزائیک مرمری حیاطی ۴۰*۴۰',
                  inSquarefeet: '۶​​/۲۵ عدد',
                  toosi: '125000',
                  red: '-',
                  yellowmix: '-',
                  shipping: '5000',
                },
              ],
            },
          ],
          [
            {
              genreEn: 'kaval',
              genreFarsi: 'كول',
              genreId: 'gerd',
              type: 'گرد',
              img: '/images/kaval/mobile/2gerd.jpg',
              sizes: [
                 {
                  type: '70',
                  price: '220000',
                  shipping: '20000',
                },
                {
                  type: '80',
                  price: '250000',
                  shipping: '20000',
                },
                 {
                  type: '90',
                  price: '325000',
                  shipping: '20000',
                },
                 {
                  type: '100',
                  price: '425000',
                  shipping: '20000',
                },
                 {
                  type: '110',
                  price: '450000',
                  shipping: '20000',
                },
                 {
                  type: '120',
                  price: '500000',
                  shipping: '20000',
                },
                 {
                  type: '130',
                  price: '660000',
                  shipping: '20000',
                },
                 {
                  type: 'دوتکه 100',
                  price: '425000',
                  shipping: '20000',
                },
              ],
            },
            {
                genreEn: 'kaval',
              genreId: 'anbari',
              type: 'انباری',
              img: '/images/kaval/mobile/2anbari.jpg',
              sizes: [
               {
                  type: 'دوتکه 100',
                  price: '425000',
                  shipping: '20000',
                },
                {
                  type: '100',
                  price: '425000',
                  shipping: '20000',
                },
                 {
                  type: '110',
                  price: '450000',
                  shipping: '20000',
                },
                 {
                  type: '120',
                  price: '500000',
                  shipping: '20000',
                },
                {
                  type: '140',
                  price: '605000',
                  shipping: '20000',
                },
              ],
            },
            {
                genreEn: 'kaval',
              genreId: 'kanaly',
              type: 'بیضی',
              img: '/images/kaval/mobile/beyzi.jpg',
              sizes: [
                {
                  type: '120',
                  price: '495000',
                  shipping: '20000',
                },
              ],
            },
            {
                genreEn: 'kaval',
              genreId: 'takhte',
              type: 'تخته',
              img: '/images/kaval/mobile/takhte.jpg',
              sizes: [
                {
                  type: '100*25*5',
                  price: '220000',
                  shipping: '20000',
                },
              ],
            },
          ],
          [
            {
              genreEn: 'mobloman',
              genreFarsi: 'مبلمان شهري',
              genreId: '#',
              type: '#',
              img: '/images/kaval/mobile/2gerd.jpg',
              sizes: [],
            },
          ],
    [
        {
            genreEn: 'newJersey',
            genreFarsi: 'نيوجرسی',
            genreId: '#',
            type: 'گرد',
            img: '/images/kaval/mobile/2gerd.jpg',
            sizes: [],
        },
    ]
];
export default data;
